### ISSUE TITLE
Awesome project!

### ISSUE THREAD

**Issue by ruyadorno** [laruche/audiotolunii#2]
Thank you for sharing this 😄  Très très beau travail! Je viens de convertir le podcast préféré de mon garçon à la boite lunii avec l'aide de ce projet 🎁 Made my day!

Je vais essayer de contribuer quelques patches dont j'ai eu besoin pour que le tout ça fonctionne. 😊 

Merci encore!

**Comment by laruche** [comment]
Hello content d'avoir pu aider un papa !
Je merge avec le projet :) 
N'hésite pas si tu veux continuer l'amélioration !
